"""Phase 1 portfolio résumé source state.

Second domain revision for jobs.forkstech.com. Adds the mutable
``resume_source_state`` table defined by specification v0.13 section 04 that
holds the current HTTP/source observation state for one exact
``(variant, source_kind, source_url)`` source, separately from the immutable
``resume_version`` historical scoring provenance.

This revision is structural only: it defines one new table, its named primary
key, the two enumerated check constraints mirror-imaged from
``resume_version``, the named composite unique constraint that is the sole
lookup key the résumé sync uses to find or create its matching row, and the
named ``ON DELETE RESTRICT`` foreign key back to ``resume_version.id``. It does
not introduce SQLAlchemy ORM models, application behavior, fetch/extraction
logic, or any out-of-scope feature.

Every constraint and backing index carries an explicit stable ``name=`` so the
catalog is deterministic and so the PostgreSQL enforcement and migration-module
tests can refer to them. No trigger is added: the application sets
``updated_at`` explicitly on every state update.

The revision is fully reversible: ``upgrade`` creates exactly
``resume_source_state`` and ``downgrade`` drops exactly that table, leaving
``0001_core_schema``'s tables and indexes untouched.

Revision ID: 0002_resume_source_state
Revises: 0001_core_schema
Create Date: 2026-07-25 22:01
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_resume_source_state"
down_revision: str | None = "0001_core_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Stable check-constraint names mirroring the enumerated domains on
# ``resume_version`` (see revision 0001_core_schema) so a source-state row can
# never carry a variant or source_kind the scoring provenance table rejects.
_RESUME_VARIANT_CHECK = "variant in ('base','product','program','technical')"
_RESUME_SOURCE_KIND_CHECK = "source_kind in ('portfolio_pdf','manual','n8n')"


def upgrade() -> None:
    op.create_table(
        "resume_source_state",
        # ``bigint generated by default as identity`` per specification v0.13
        # section 04. The named primary-key constraint below is the sole PK
        # definition; no inline ``primary_key=True`` is used on the column.
        sa.Column(
            "id",
            sa.BigInteger,
            sa.Identity(always=False),
        ),
        sa.Column("variant", sa.Text, nullable=False),
        sa.Column("source_kind", sa.Text, nullable=False),
        sa.Column("source_url", sa.Text, nullable=False),
        sa.Column("source_etag", sa.Text),
        sa.Column("source_last_modified", sa.TIMESTAMP(timezone=True)),
        sa.Column("last_checked_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_body_fetched_at", sa.TIMESTAMP(timezone=True)),
        sa.Column("last_body_sha256", sa.Text),
        sa.Column("current_resume_version_id", sa.BigInteger),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="resume_source_state_pkey"),
        sa.CheckConstraint(
            _RESUME_VARIANT_CHECK,
            name="resume_source_state_variant_check",
        ),
        sa.CheckConstraint(
            _RESUME_SOURCE_KIND_CHECK,
            name="resume_source_state_source_kind_check",
        ),
        sa.UniqueConstraint(
            "variant",
            "source_kind",
            "source_url",
            name="resume_source_state_variant_source_kind_source_url_key",
        ),
        sa.ForeignKeyConstraint(
            ["current_resume_version_id"],
            ["resume_version.id"],
            name="resume_source_state_current_resume_version_id_fkey",
            ondelete="RESTRICT",
        ),
    )


def downgrade() -> None:
    op.drop_table("resume_source_state")
